package vn.id.thongdanghoang.user_service.utils;

import java.beans.IntrospectionException;
import java.beans.Introspector;
import java.lang.reflect.InvocationTargetException;
import java.util.Arrays;
import java.util.Optional;

import org.hibernate.Hibernate;

import lombok.AccessLevel;
import lombok.NoArgsConstructor;

@NoArgsConstructor(access = AccessLevel.PRIVATE)
public class JpaUtils {

    /**
     * Initializes a Hibernate entity by touching its graph. Queries generated by this touch will
     * therefore fully respect what have been configured at entity mapping level.
     *
     * @param result The entity itself.
     * @param associations List of associations to be initialized.
     * @return The entity (for convenient coding).
     */
    public static <T> T initialize(T result, String... associations) {
        if (result == null) {
            return null;
        }
        for (var association : associations) {
            initializeInternal(result, association);
        }
        return result;
    }

    private static void initializeInternal(Object result, String association) {
        try {
            var bi = Introspector.getBeanInfo(result.getClass());
            var propertyDescriptors = Arrays
                    .stream(bi.getPropertyDescriptors())
                    .filter(propertyDescriptor -> association.equals(propertyDescriptor.getName()))
                    .toList();
            for (var md : propertyDescriptors) {
                Optional.ofNullable(md.getReadMethod().invoke(result)).ifPresent(Hibernate::initialize);
            }
        } catch (IntrospectionException | IllegalAccessException | IllegalArgumentException | InvocationTargetException e) {
            throw new RuntimeException("Error occurred while initializing.", e);
        }
    }

}
