quarkus:
  datasource:
    metrics:
      enabled: true
    username: ${QUARKUS_DATASOURCE_USERNAME}
    password: ${QUARKUS_DATASOURCE_PASSWORD}
    db-kind: postgresql
    reactive:
      url: vertx-reactive:postgresql://localhost:8079/prodcat
  hibernate-orm:
    log:
      sql: false
      format-sql: false
    database:
      generation: validate
    physical-naming-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
  log:
    console:
      format: "%d{yyyy-MM-dd HH:mm:ss,SSS} %-5p [%c{3.}] %X (%t) %s%e%n"
hibernate:
  query:
    fail_on_pagination_over_collection_fetch: true
"%dev":
  quarkus:
    datasource:
      username: quarkus
      password: quarkus
      devservices:
        enabled: true
        show-logs: true
        port: 8079
        db-name: prodcat
    hibernate-orm:
      log:
        sql: true
        format-sql: false
      database:
        generation: update